"""
Recursos y configuraciones del sistema Velora: prompts para LLMs.
"""

from .prompts import (
    PROMPT_EXTRACCION_REQUISITOS, PROMPT_MATCHING_CV,
    PROMPT_EVALUAR_RESPUESTA, PROMPT_SISTEMA_AGENTE,
    PROMPT_SALUDO_AGENTE, PROMPT_PREGUNTA_AGENTE, PROMPT_CIERRE_AGENTE,
    EXTRACT_REQUIREMENTS_PROMPT, MATCH_CV_REQUIREMENTS_PROMPT,
    EVALUATE_RESPONSE_PROMPT, AGENTIC_SYSTEM_PROMPT,
    AGENTIC_GREETING_PROMPT, AGENTIC_QUESTION_PROMPT, AGENTIC_CLOSING_PROMPT,
)

__all__ = [
    "PROMPT_EXTRACCION_REQUISITOS", "PROMPT_MATCHING_CV",
    "PROMPT_EVALUAR_RESPUESTA", "PROMPT_SISTEMA_AGENTE",
    "PROMPT_SALUDO_AGENTE", "PROMPT_PREGUNTA_AGENTE", "PROMPT_CIERRE_AGENTE",
    "EXTRACT_REQUIREMENTS_PROMPT", "MATCH_CV_REQUIREMENTS_PROMPT",
    "EVALUATE_RESPONSE_PROMPT", "AGENTIC_SYSTEM_PROMPT",
    "AGENTIC_GREETING_PROMPT", "AGENTIC_QUESTION_PROMPT", "AGENTIC_CLOSING_PROMPT",
]
